apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent-deployment
  labels:
    app: torrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torrent
  template:
    metadata:
      labels:
        app: torrent
    spec:
      containers:
        - name: torrent
          image: registry.digitalocean.com/swensson/torrent
          ports:
            - containerPort: 30162
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-service
spec:
  type: NodePort
  selector:
    app: torrent
  ports:
    - protocol: TCP
      port: 30162
      targetPort: 30162
      nodePort: 30162
      name: test
    - protocol: TCP
      port: 30163
      targetPort: 30163
      nodePort: 30163
      name: test2
